### ISSUE TITLE
module 'dataset' has no attribute 'get_dataloaders'

### ISSUE THREAD

**Issue by muyinjiangxue** [bbrattoli/ZeroShotVideoClassification#2]
dataloaders = dataset.get_dataloaders(opt)

The data loading method here is not seen in dataset.

**Comment by nanguoshun** [comment]
@bbrattoli dear Biagio, I am suffering the same issue. Would you please help to fix it?

Is it get_datasets() instead of get_dataloaders()  @muyinjiangxue 

Thanks a lot!

**Comment by KP1-cmd** [comment]
hello @nanguoshun I am suffering the same issue.
datasets = dataset.get_datasets(opt) or  dataloaders = dataset.get_datasets(opt)

can you tell me which one is correct ?
i tried both but still get the error

Total batch size: 22
UCF101: total number of videos 13320, classes 101
HMDB51: total number of videos 6766, classes 51
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    datasets = dataset.get_datasets(opt)
  File "/home/hermes/Downloads/ZeroShotVideoClassification-master/dataset.py", line 14, in get_datasets
    get_datasets = get_both_datasets(opt)
  File "/home/hermes/Downloads/ZeroShotVideoClassification-master/dataset.py", line 107, in get_both_datasets
    train_fnames, train_labels, train_classes = get_kinetics(opt.dataset)
  File "/home/hermes/Downloads/ZeroShotVideoClassification-master/auxiliary/auxiliary_dataset.py", line 46, in get_kinetics
    with open('/home/hermes/Downloads/ZeroShotVideoClassification-master/assets/kinetics%s.txt' % n_classes, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hermes/Downloads/ZeroShotVideoClassification-master/assets/kinetics400.txt'

**Comment by nanguoshun** [comment]
hi @KP1-cmd , I have no idea for the issues. I suggest we send emails to authors for the issues.

Thanks a lot!

**Comment by KP1-cmd** [comment]
> hi @KP1-cmd , I have no idea for the issues. I suggest we send emails to authors for the issues.
> 
> Thanks a lot!

Ok thank you

**Comment by KP1-cmd** [comment]
@muyinjiangxue did you fix the error ?

**Comment by bbrattoli** [comment]
The issue comes from the fact that “get_kinetics()” in auxiliary/auxiliary_dataset.py, needs to be adapted to your format used for the Kinetics dataset. When I implemented this code I used a dataset from the AWS team and I am not allowed to publish that. I suggest you fix the get_kinetics and debug the dataloader accordingly. Unfortunately Kinetics is not an easy dataset to work with. 

A quicker solution is to download one of the model that I trained and only evaluate or fine-tune on UCF101.

Thank you for pointing this out, I will mention it in the readme.

Cheers,
Biagio

P.S. Sorry for the late reply

**Comment by muyinjiangxue** [comment]
Your answer makes me understand. Thank you very much for your reply！Everything is very good




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Biagio Brattoli"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月14日(星期天) 晚上9:51
收件人:&nbsp;"bbrattoli/ZeroShotVideoClassification"<ZeroShotVideoClassification@noreply.github.com&gt;;
抄送:&nbsp;"西瓜她说爱夏天"<462001974@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bbrattoli/ZeroShotVideoClassification] module 'dataset' has no attribute 'get_dataloaders' (#2)





 
The issue comes from the fact that “get_kinetics()” in auxiliary/auxiliary_dataset.py, needs to be adapted to your format used for the Kinetics dataset. When I implemented this code I used a dataset from the AWS team and I am not allowed to publish that. I suggest you fix the get_kinetics and debug the dataloader accordingly. Unfortunately Kinetics is not an easy dataset to work with.
 
A quicker solution is to download one of the model that I trained and only evaluate or fine-tune on UCF101.
 
Thank you for pointing this out, I will mention it in the readme.
 
Cheers,
 Biagio
 
P.S. Sorry for the late reply
